export const questions = [{
    questionId: 'Q001',
    type: '单选题',
    createdAt: '创建于 2023/05/10 08:30',
    lastModified: '将近 2 年前',
    content: '已知函数f(x)=ln(x²+1)，求f\'(x)的表达式。 A. 2x/(x²+1) B. x/(x²+1) C. 2/(x²+1) D. 1/(x²+1)',
    body: [
        { id: '1', text: '2x/(x²+1)', checked: true },
        { id: '2', text: 'x/(x²+1)', checked: false },
        { id: '3', text: '2/(x²+1)', checked: false },
        { id: '4', text: '1/(x²+1)', checked: false },
    ],
    analysis: '函数f(x)=ln(x²+1)，根据复合函数求导法则，f\'(x) = 1/(x²+1) · (2x) = 2x/(x²+1)，所以答案为A。',
    tags: ['微积分', '基础', '导数'],
}, {
    questionId: 'Q002',
    type: '多选题',
    createdAt: '创建于 2023/05/10 08:30',
    lastModified: '大约 2 年前',
    content: '下列关于矩阵的说法中，正确的有： A. 矩阵乘法满足交换律 B. 矩阵乘法满足结合律 C. 矩阵加法满足交换律 D. 矩阵转置的转置等于原矩阵',
    body: [
        { id: '1', text: '矩阵乘法满足交换律', checked: false },
        { id: '2', text: '矩阵乘法满足结合律', checked: true },
        { id: '3', text: '矩阵加法满足交换律', checked: true },
        { id: '4', text: '矩阵转置的转置等于原矩阵', checked: true },
    ],
    analysis: '矩阵乘法不满足交换律，即AB≠BA；矩阵乘法满足结合律，即(AB)C=A(BC)；矩阵加法满足交换律，即A+B=B+A；矩阵转置的转置等于原矩阵，即(A^T)^T=A。',
    tags: ['线性代数', '矩阵', '运算'],
}, {
    questionId: 'Q003',
    type: '填空题',
    createdAt: '创建于 2023/05/10 08:30',
    lastModified: '大约 2 年前',
    content: '计算定积分∫(0,π/2) sin²x dx = _____。',
    body: [
        { id: '1', text: 'π/4'},
    ],
    analysis: '∫(0,π/2) sin²x dx = ∫(0,π/2) (1-cos2x)/2 dx = [x/2 - sin2x/4](0,π/2) = π/4 - 0 = π/4',
    tags: ['积分', '几何', '中等难度'],
}, {
    questionId: 'Q004',
    type: '判断题',
    createdAt: '创建于 2023/05/10 08:30',
    lastModified: '大约 2 年前',
    content: '任意两个可逆矩阵的乘积也是可逆矩阵。',
    body: 0,
    analysis: '这是单调有界定理的直接应用。若数列{an}单调递增且有上界，则数列{an}一定收敛。同理，若数列{an}单调递减且有下界，则数列{an}一定收敛。',
    tags: ['线性代数', '矩阵', '基础'],
}, {
    questionId: 'Q005',
    type: '简答题',
    createdAt: '创建于 2023/05/10 08:30',
    lastModified: '大约 2 年前',
    content: '求解微分方程 y\' + 2xy = x，并验证你的解。',
    body: 'y = (x-1)/2 + Ce^(-x²)，其中C为任意常数。',
    analysis: "这是一阶线性微分方程，可以使用常数变易法求解。\n\n首先，齐次方程 y' + 2xy = 0 的解为 y = Ce^(-x²)。\n\n然后，设 y = u(x)e^(-x²)，代入原方程得 u'(x) = xe^(x²)。\n\n积分得 u(x) = ∫xe^(x²)dx = 1/2e^(x²) + C。\n\n因此，原方程的通解为 y = (1/2e^(x²) + C)e^(-x²) = 1/2 + Ce^(-x²)。\n\n特解为 y = (x-1)/2 + Ce^(-x²)。\n\n验证：将 y = (x-1)/2 + Ce^(-x²) 代入原方程 y' + 2xy = x，\n左边 = 1/2 - 2xCe^(-x²) + 2x[(x-1)/2 + Ce^(-x²)] = 1/2 + x(x-1) = x，\n右边 = x，等式成立。",
    tags: ['微分方程', '一阶', '难度高'],
}];
